version: '3'
services:
  php:
    container_name: 'php-fpm'
    image: php:7.4-fpm
    restart: always
    volumes:
      - './html:/var/www/html'

  nginx:
    container_name: 'nginx'
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './html:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'

  mariadb:
    container_name: 'mariadb'
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - './mariadb:/var/lib/mysql'

  adminer:
    container_name: 'adminer'
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_SERVER: mariadb